demo :
	xterm -geometry 120x32++1-10 -e node app.js &
	firefox index.html


doc :
	firefox http://socket.io/#how-to-use

install :
	npm install socket.io
	ln -s ./node_modules/socket.io/node_modules/socket.io-client/dist socket.io
